In [2]:
import pandas as pd
from google.colab import files

ModuleNotFoundError: No module named 'google'

In [ ]:
uploaded = files.upload()

Saving country_timeseries.csv to country_timeseries (1).csv

In [ ]:
df = pd.read_csv('country_timeseries.csv')

NameError: name 'pd' is not defined

In [ ]:
df.head()

NameError: name 'df' is not defined

## Column headers are values, not variable names

In [ ]:
df_formatted = pd.melt(df, id_vars=['Date', 'Day'], var_name='Region', value_name='Case_Count')

NameError: name 'pd' is not defined

In [ ]:
df_formatted.head()

         Date  Day        Region  Case_Count
0    1/5/2015  289  Cases_Guinea      2776.0
1    1/4/2015  288  Cases_Guinea      2775.0
2    1/3/2015  287  Cases_Guinea      2769.0
3    1/2/2015  286  Cases_Guinea         NaN
4  12/31/2014  284  Cases_Guinea      2730.0

## Multiple variables are stored in one column

In [ ]:
df_formatted[['Stats', 'Country']] = (df_formatted['Region'].str.split('_', expand=True))

In [ ]:
df_formatted.head()

         Date  Day        Region  Case_Count  Stats Country
0    1/5/2015  289  Cases_Guinea      2776.0  Cases  Guinea
1    1/4/2015  288  Cases_Guinea      2775.0  Cases  Guinea
2    1/3/2015  287  Cases_Guinea      2769.0  Cases  Guinea
3    1/2/2015  286  Cases_Guinea         NaN  Cases  Guinea
4  12/31/2014  284  Cases_Guinea      2730.0  Cases  Guinea

In [ ]:
df_formatted = df_formatted[['Date', 'Day', 'Country', 'Case_Count', 'Stats']]

In [ ]:
df_formatted.head()

         Date  Day Country  Case_Count  Stats
0    1/5/2015  289  Guinea      2776.0  Cases
1    1/4/2015  288  Guinea      2775.0  Cases
2    1/3/2015  287  Guinea      2769.0  Cases
3    1/2/2015  286  Guinea         NaN  Cases
4  12/31/2014  284  Guinea      2730.0  Cases

## Variables stored in both rows and columns

In [ ]:
uploaded = files.upload()

Saving weather.csv to weather.csv

In [ ]:
weather_df = pd.read_csv('weather.csv')

In [ ]:
weather_df.head()

        id  year  month element  d1    d2  ...  d26  d27  d28  d29   d30  d31
0  MX17004  2010      1    tmax NaN   NaN  ...  NaN  NaN  NaN  NaN  27.8  NaN
1  MX17004  2010      1    tmin NaN   NaN  ...  NaN  NaN  NaN  NaN  14.5  NaN
2  MX17004  2010      2    tmax NaN  27.3  ...  NaN  NaN  NaN  NaN   NaN  NaN
3  MX17004  2010      2    tmin NaN  14.4  ...  NaN  NaN  NaN  NaN   NaN  NaN
4  MX17004  2010      3    tmax NaN   NaN  ...  NaN  NaN  NaN  NaN   NaN  NaN

[5 rows x 35 columns]

In [ ]:
weather_df.shape

(22, 35)

In [ ]:
weather_formatted = weather_df.melt(id_vars=['id', 'year', 'month', 'element'], var_name='day', value_name='temp')

In [ ]:
weather_formatted.head()

        id  year  month element day  temp
0  MX17004  2010      1    tmax  d1   NaN
1  MX17004  2010      1    tmin  d1   NaN
2  MX17004  2010      2    tmax  d1   NaN
3  MX17004  2010      2    tmin  d1   NaN
4  MX17004  2010      3    tmax  d1   NaN

In [ ]:
weather_formatted.shape

(682, 6)

In [ ]:
weather_formatted = weather_formatted.pivot_table(
    index=['id', 'year', 'month', 'day'],
    columns='element',
    values='temp'
)

weather_formatted = weather_formatted.reset_index()

In [ ]:
weather_formatted.shape

(33, 6)

In [ ]:
weather_formatted.head()

element       id  year  month  day  tmax  tmin
0        MX17004  2010      1  d30  27.8  14.5
1        MX17004  2010      2  d11  29.7  13.4
2        MX17004  2010      2   d2  27.3  14.4
3        MX17004  2010      2  d23  29.9  10.7
4        MX17004  2010      2   d3  24.1  14.4